### PR TITLE
Build Challenge Submission

### PR DESCRIPTION
**Pull request by sajjad2881**
Name: Sajjad Zafar 
Uni: sz2881

### CODE REVIEW

**Comment by Dweej-Patel** [comment]
Thank you so much for your interest in joining Columbia Build Lab this coming Spring! We are looking forward to getting to know you and would like to schedule an interview (20 mins) with you. Please indicate your availability [here](https://www.when2meet.com/?10484776-xjdoH) and we will follow up with a calendar invite. 

The chat will cover:
- Introduction and background 
- Your interest 
- Technical skills  
- Questions 

Thank you so much and look forward to meeting you!

**Comment by Dweej-Patel** [comment]
Please disregard the previous when2meet link. Here is an updated link ([link](https://www.when2meet.com/?10593650-QvTu4)) to indicate your availability.

**Comment by sajjad2881** [comment]
Hi! I filled out the when2meet. I am in a different time zone so mornings work better for me; however, if that is not possible, please let me know!

How should I prepare for the interview? Is it a technical or a normal conversation?

Thank you!

Best,
Sajjad.

--


Sajjad Zafar
Computer Science and Economics
Columbia University | Class of 2023

70 Morningside Drive
2787 Columbia Student Mail
New York, NY 10027-7236
+92 349 3805657

**Comment by Dweej-Patel** [comment]
Mornings are perfectly fine. The interview will mostly be conversational, we just want to know you better. You don't have to prepare anything for the interview.

**Pull request closed without merging**
